#!/bin/bash

service ddg-idd-driver stop

rm -f /etc/ddg-idd-driver/ddg-idd-driver.log
# rm -f /etc/ddg-idd-driver/ddg_states.json
# rm -f /etc/ddg-idd-driver/idd_states.json
# rm -fr /etc/ddg-idd-driver/__pycache__