ddg_devices: []
#    - name: "bDDGf0r0_bDDGf0r0_27_n1_DDG"
#      model: "User model name"
#      is_panel: "False"
#    - name: "bDDGf0r0_bDDGf0r0_27_n2_DDG"
#      model: "User model name"
#      is_panel: "False"
